print("hello world")
print("what is your name?")
my_name = input()
print("It is good to meet you, " + my_name)
print("the length of your name is : ")
print(len(my_name))
print("what is your age?")
my_age = input()
print("you whill be " + str(int(my_age)+1)+ " in a year.")